name: 'APIDoctor'
description: 'Openapi spec linter'
inputs:
  spec:
    description: 'path to the openapi spec file'
    required: true
  options:
    description: 'additional options to be passed to the lint subcommand'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.options }}
    - ${{ inputs.spec }}
